
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import configparser
import threading
import queue
import time
from pathlib import Path
from pigpio_encoder.rotary import Rotary
import RPi.GPIO as GPIO



# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter
from tkinter.constants import DISABLED


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

# Stop offsets 1
OFFSET_1 = 0
OFFSET_2 = 200
OFFSET_3 = 480
OFFSET_4 = 800

PIN_UP = 20
PIN_DOWN = 21

PIN_REMOTE_START = 23
PIN_REMOTE_STOP = 24


class GUI():

    def __init__(self,parent):
        self.str_angle = str()
        self.stop_offset = float()
        self.stop_value = float()
        self.fl_set_angle = float()
        self.fl_current_angle = float()
        self.config = configparser.ConfigParser()
        self.window = parent    
        self.config.read('Settings.INI')
        self.run_bending = True
        self.running = True
        # self.fl_set_angle = float(config['DEFAULT']['SetAngle'])
        #---------------initialize Encoder -----------------
        self.enc = Rotary(clk_gpio=15, dt_gpio=18, sw_gpio=14)
        self.enc.setup_rotary(rotary_callback=self.get_angle, max=16000, debounce=10)
        #-----------------initialize Relay Pins-----------------
        GPIO.setmode(GPIO.BCM)
        GPIO.setup(PIN_UP, GPIO.OUT)
        GPIO.setup(PIN_DOWN, GPIO.OUT)
        #----------------initialize Remote Pins-----------------
        # GPIO.setup(PIN_REMOTE_START, GPIO.IN, pull_up_down=GPIO.PUD_UP)
        # GPIO.add_event_detect(PIN_REMOTE_START, GPIO.FALLING, callback =self.start_bending, bouncetime=100)
        # GPIO.setup(PIN_REMOTE_STOP, GPIO.IN, pull_up_down=GPIO.PUD_UP)
        # GPIO.add_event_detect(PIN_REMOTE_STOP, GPIO.FALLING, callback =self.stop_bending, bouncetime=100)
        

        #--------------- create GUI items ------------------

        self.canvas = Canvas(
            self.window,
            bg = "#FFFFFF",
            height = 800,
            width = 1280,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.button_image_1 = PhotoImage(
            file=self.relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.stop_bending(),
            relief="flat"
        )
        self.button_1.place(
            x=484.0,
            y=645.0,
            width=265.0,
            height=100.0
        )

        self.button_image_2 = PhotoImage(
            file=self.relative_to_assets("button_2.png"))
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.start_bending(),
            relief="flat"
        )
        self.button_2.place(
            x=114.0,
            y=645.0,
            width=265.0,
            height=100.0
        )

        self.button_image_3 = PhotoImage(
            file=self.relative_to_assets("button_3.png"))
        self.button_3 = Button(
            bg = "#FFFFFF",
            image=self.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.change_stop_offset(4),
            relief="flat",
        )
        self.button_3.place(
            x=644.0,
            y=495.0,
            width=100.0,
            height=100.0
        )


        self.button_image_4 = PhotoImage(
            file=self.relative_to_assets("button_4.png"))
        self.button_4 = Button(
            bg = "#FFFFFF",
            image=self.button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.change_stop_offset(3),
            relief="flat",

        )
        self.button_4.place(
            x=484.0,
            y=495.0,
            width=100.0,
            height=100.0
        )


        self.button_image_5 = PhotoImage(
            file=self.relative_to_assets("button_5.png"))
        self.button_5 = Button(
            bg = "#FFFFFF",
            image=self.button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.change_stop_offset(2),
            relief="flat"
        )
        self.button_5.place(
            x=284.0,
            y=495.0,
            width=100.0,
            height=100.0
        )

        self.button_image_6 = PhotoImage(
            file=self.relative_to_assets("button_6.png"))
        self.button_6 = Button(
            bg = "grey",
            image=self.button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.change_stop_offset(1),
            relief="flat"
        )
        self.button_6.place(
            x=114.0,
            y=495.0,
            width=100.0,
            height=100.0
        )

        self.button_image_7 = PhotoImage(
            file=self.relative_to_assets("button_7.png"))
        self.button_7 = Button(
            image=self.button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('Enter'),
            relief="flat",
            state="disabled"
        )
        self.button_7.place(
            x=791.0,
            y=645.0,
            width=380.0,
            height=100.0
        )

        self.button_image_8 = PhotoImage(
            file=self.relative_to_assets("button_8.png"))
        self.button_8 = Button(
            image=self.button_image_8,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('0'),
            relief="flat"
        )
        self.button_8.place(
            x=791.0,
            y=495.0,
            width=100.0,
            height=100.0
        )

        self.button_image_9 = PhotoImage(
            file=self.relative_to_assets("button_9.png"))
        self.button_9 = Button(
            image=self.button_image_9,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('.'),
            relief="flat"
        )
        self.button_9.place(
            x=931.0,
            y=495.0,
            width=100.0,
            height=100.0
        )
        self.button_image_10 = PhotoImage(
            file=self.relative_to_assets("button_10.png"))
        self.button_10 = Button(
            image=self.button_image_10,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('C'),
            relief="flat"
        )
        self.button_10.place(
            x=1071.0,
            y=495.0,
            width=100.0,
            height=100.0
        )

        self.button_image_11 = PhotoImage(
            file=self.relative_to_assets("button_11.png"))
        self.button_11 = Button(
            image=self.button_image_11,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('7'),
            relief="flat"
        )
        self.button_11.place(
            x=791.0,
            y=355.0,
            width=100.0,
            height=100.0
        )

        self.button_image_12 = PhotoImage(
            file=self.relative_to_assets("button_12.png"))
        self.button_12 = Button(
            image=self.button_image_12,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('8'),
            relief="flat"
        )
        self.button_12.place(
            x=931.0,
            y=355.0,
            width=100.0,
            height=100.0
        )

        self.button_image_13 = PhotoImage(
            file=self.relative_to_assets("button_13.png"))
        self.button_13 = Button(
            image=self.button_image_13,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('9'),
            relief="flat"
        )
        self.button_13.place(
            x=1071.0,
            y=355.0,
            width=100.0,
            height=100.0
        )

        self.button_image_14 = PhotoImage(
            file=self.relative_to_assets("button_14.png"))
        self.button_14 = Button(
            image=self.button_image_14,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('4'),
            relief="flat"
        )
        self.button_14.place(
            x=791.0,
            y=215.0,
            width=100.0,
            height=100.0
        )

        self.button_image_15 = PhotoImage(
            file=self.relative_to_assets("button_15.png"))
        self.button_15 = Button(
            image=self.button_image_15,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('5'),
            relief="flat"
        )
        self.button_15.place(
            x=931.0,
            y=215.0,
            width=100.0,
            height=100.0
        )

        self.button_image_16 = PhotoImage(
            file=self.relative_to_assets("button_16.png"))
        self.button_16 = Button(
            image=self.button_image_16,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('6'),
            relief="flat"
        )
        self.button_16.place(
            x=1071.0,
            y=215.0,
            width=100.0,
            height=100.0
        )
        self.button_image_17 = PhotoImage(
            file=self.relative_to_assets("button_17.png"))
        self.button_17 = Button(
            image=self.button_image_17,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('3'),
            relief="flat"
        )
        self.button_17.place(
            x=1071.0,
            y=75.0,
            width=100.0,
            height=100.0
        )
        self.button_image_18 = PhotoImage(
            file=self.relative_to_assets("button_18.png"))
        self.button_18 = Button(
            image=self.button_image_18,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('2'),
            relief="flat"
        )
        self.button_18.place(
            x=931.0,
            y=75.0,
            width=100.0,
            height=100.0
        )

        self.button_image_19 = PhotoImage(
            file=self.relative_to_assets("button_19.png"))
        self.button_19 = Button(
            image=self.button_image_19,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_digit_to_angle('1'),
            relief="flat"
        )
        self.button_19.place(
            x=791.0,
            y=75.0,
            width=100.0,
            height=100.0
        )

        self.canvas.create_rectangle(
            451.0,
            355.0,
            751.0,
            455.0,
            fill="#C4C4C4",
            outline="")

        self.leng_stop = self.canvas.create_text(
            601.0,
            405.0,
            anchor="center",
            text="0.0",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )

        self.canvas.create_text(
            114.0,
            405.0,
            anchor="w",
            text="Anschlag:",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )

        self.canvas.create_rectangle(
            451.0,
            215.0,
            751.0,
            315.0,
            fill="#C4C4C4",
            outline="")

        self.current_angle = self.canvas.create_text(
            601.0,
            265.0,
            anchor="center",
            text="0°",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )

        self.canvas.create_text(
            114.0,
            265.0,
            anchor="w",
            text="Ist:",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )

        self.canvas.create_rectangle(
            451.0,
            75.0,
            751.0,
            175.0,
            fill="#C4C4C4",
            outline="")

        self.set_angle = self.canvas.create_text(
            601.0,
            125.0,
            anchor="center",
            text="0°",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )

        self.canvas.create_text(
            109.0,
            125.0,
            anchor="w",
            text="Soll:",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )
        # self.thread_angle=threading.Thread(target=self.get_angle).start()

    def relative_to_assets(self, path: str) -> Path:
        return ASSETS_PATH / Path(path)

    def add_digit_to_angle(self, value):

        if value == 'C':
            self.str_angle = str()
            self.canvas.itemconfig(self.set_angle, text=''.join([self.str_angle,'°']))
            self.button_7['state']='disable'
            return

        if value == 'Enter':
            self.change_angle(self.str_angle)
            self.str_angle = str()
            self.button_7['state']='disable'
            return

        self.str_angle = self.str_angle + value
        self.canvas.itemconfig(self.set_angle, text=''.join([self.str_angle,'°']))
        self.button_7['state']='normal'

    def change_angle(self, angle):
        try:
            self.result = eval(angle)
            print(self.result)
            self.canvas.itemconfig(self.set_angle, text=''.join([str(self.result),'°']))
            self.fl_set_angle = float(self.result)
            # config['DEFAULT']['SetAngle'] = str(result)
            # with open('Settings.INI', 'w') as configfile:    # save to configfile
            #     config.write(configfile)

        except Exception as e:
            print(e)
            self.canvas.itemconfig(self.set_angle, text='Error')

    def change_selected_button(self, button):
        self.button_3["bg"]="white"
        self.button_4["bg"]="white"
        self.button_5["bg"]="white"
        self.button_6["bg"]="white"
        button["bg"]="grey"
        return

    def change_stop_offset(self, value):
        if value == 1:
            self.stop_offset = OFFSET_1
            self.change_selected_button(self.button_6)
        elif value == 2:
            self.stop_offset = OFFSET_2
            self.change_selected_button(self.button_5)
        elif value == 3:
            self.stop_offset = OFFSET_3
            self.change_selected_button(self.button_4)
        elif value == 4:
            self.stop_offset = OFFSET_4
            self.change_selected_button(self.button_3)
        str_offset= str(self.stop_offset)
        print(''.join(["Aktueller Anschlagoffset: ", str_offset]))
        self.display_leng_stop()
        return

    def display_leng_stop(self):
        self.canvas.itemconfig(self.leng_stop, text=str(self.stop_value + self.stop_offset))

    def start_bending(self,channel=0):
        self.run_bending = True
        threading.Thread(target=self.bend,args=[self.fl_set_angle]).start()
        self.button_2["state"] = "disabled"
        return

    def bend(self, set_angle):
        while self.run_bending == True :

            while(self.fl_current_angle < set_angle and self.run_bending==True):
                    # print("Moving up")
                    GPIO.output(PIN_UP,1)
                    time.sleep(0.0001)
                    # print(self.fl_current_angle)
            GPIO.output(PIN_UP,0)

            while(self.fl_current_angle > 0 and self.run_bending==True):
                    # print("Moving down")
                    GPIO.output(PIN_DOWN,1)
                    time.sleep(0.0001)
            GPIO.output(PIN_DOWN,0)
            self.run_bending = False
            self.button_2["state"] = "normal"
            return
        self.button_2["state"] = "normal"
        return

    def stop_bending(self,channel=0):
        self.run_bending = False
        GPIO.output(PIN_UP,0)
        GPIO.output(PIN_DOWN,0)
        print("Bending is stopped")

    def get_angle(self, angle):
        # while(self.running==True):
        #     angle = self.enc.read()/40
        #     if self.fl_current_angle != angle:
        #         self.fl_current_angle = angle
        #         self.canvas.itemconfigure(self.current_angle, text=''.join([f'{angle:.1f}',"°"]))
        #     time.sleep(0.0001)
        self.fl_current_angle = angle/10
        self.canvas.itemconfigure(self.current_angle, text=''.join([f'{angle/10:.1f}',"°"]))


    def on_closing(self):
        self.running = False
        self.run_bending = False
        GPIO.cleanup()
        self.window.destroy()

# -------------------- Start Mainloop --------------------



if __name__ == "__main__":
    window = Tk()
    # window.attributes("-fullscreen", True) 
    window.geometry("1280x800")
    window.configure(bg = "#FFFFFF")
    window.resizable(True, True)
    gui = GUI(window)
    window.protocol("WM_DELETE_WINDOW", gui.on_closing)
    window.mainloop()

